- README.md
- backend/.env
- backend/.gitignore
- backend/Dockerfile
- backend/example.env
- backend/package.json
- backend/src/config/db.js
- backend/src/routes/example.js
- backend/src/server.js
- db/database.sql
- docker-compose.yml
- web/.env
- web/.gitignore
- web/Dockerfile
- web/example.env
- web/src/components/Schedule/Schedule.jsx
- web/src/helpers/api.js
Closes: https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/41
Closes: https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/42
> feat(backend & db): init backend and db

- backend/src/routes/event.js
- backend/src/server.js
- db/database.sql
- web/src/components/Schedule/Schedule.jsx
- web/src/helpers/api.js
Still needs a bit of work but better to have an example now. Will polish it in another PR
Closes: https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/68
Closes: https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/56
Contributes: https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/62
> feat(web & backend & db): add event creation

- backend/src/routes/event.js
Closes: https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/59
Contributes: #5
> add (unique) event backend PUT endpoint

- backend/src/routes/event.js
- db/database.sql
- web/src/components/Schedule/Schedule.jsx
- web/src/helpers/api.js
- attributes have been added to the database 
- checkboxes added for isRecurring and isPrivate
> Create recurring event backend completed

- web/testing/.gitignore
- web/testing/cypress.config.js
- web/testing/cypress/e2e/navigation.cy.js
- web/testing/cypress/fixtures/example.json
- web/testing/cypress/support/commands.js
- web/testing/cypress/support/e2e.js
- web/testing/package.json
This adds cypress, it will allow us to easily create integration tests for the entire app
Cypress basically is like a browser that goes around and actually uses the app, clicks on stuff, and asserts that the right things are happening, this also means that it will create all the videos we need for us, with details on what it is doing 😄
> test(web): setup end to end/integration testing

- web/src/components/Schedule/Schedule.jsx
Closes: https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/57
Closes: https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/55
Closes: https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/3
very basic, the schedule still needs to be polished...a lot (automatically set it to cur date, make it loop better and fit the theme etc...)
But this closes the functional aspect of issues above, ease of use and aesthetics can come later...
> feat(web): remap to create event

- web/testing/cypress/e2e/ID001_Create_Unique_Event.cy.js
> test(web): create unique event e2e

- web/src/components/Auth/Login.jsx
- web/src/components/Navbar/Navbar.jsx
this shouldn't have an impact on the in-progress tests, but  will make things look much cleaner
> feat(web): remove example path, center login button

- web/testing/cypress/e2e/ID004_Create_Recurring_Event.cy.js
Created the test for simply creating a recurring event
> Test create recurring event 

- Gherkin Features/ID005_Edit_Unique_Event.feature
- Gherkin Features/ID006_Edit_Recurring_Event.feature
- web/src/components/Schedule/Schedule.jsx
- web/testing/cypress/e2e/ID005_Edit_Unique_Event.cy.js
- web/testing/cypress/e2e/ID006_Edit_Recurring_Event.cy.js
Added 2 more tests for the scenarios when you edit an event with invalid dates
> test(web): edit event error flow

- web/testing/cypress/e2e/ID002_Display_Schedule.cy.js
> E2e002 test display schedule

- web/src/components/Auth/AccountInfo.jsx
- web/testing/cypress/e2e/ID010_Update_User_Information.cy.js
Closes: https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/116
> Test: Update User Information

- Gherkin Features/ID013_Adding_course_event_using_code.feature
Closes: https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/127
> chore(gherkin): create ID013, adding course event using course code

- backend/src/routes/friendGroup.js
- backend/src/server.js
- db/database.sql
I didn't test the code yet, but in case people want to use the rest methods in the meantime that I create the frontend side
> Added db and backend to create group of friends

- backend/src/routes/friendship.js
- backend/src/server.js
- db/database.sql
- web/src/components/Friendship/Friendship.jsx
- web/src/components/Navbar/Navbar.jsx
- web/src/helpers/api.js
- web/src/index.jsx
Friendship gets created + error handling for the following cases: 
1. user does not exist when you search them
2. You can't add yourself as a friend
3. You can't add someone twice
How i tried it: 
To create friendships, I logged in to two different accounts and completed my profile for both; after that i search up the other in the search page and add them as friend
> feat: connection between users (Id014)

- backend/src/routes/friendship.js
- web/src/components/Friendship/Friendship.jsx
- web/src/helpers/api.js
Delete a friendship feature
- Successful delete message pop-up
Error handling for the case:
- Attempt to delete a user that is not in friend list
How I tested it:
1. Logged in two different accounts and completed profiles for both
2. Tried out the different delete cases
> feat: unfriend another user (ID021)

- backend/src/routes/event.js
- backend/src/routes/friendGroup.js
- backend/src/routes/friendship.js
- backend/src/routes/users.js
- backend/src/server.js
- db/database.sql
- web/src/components/Common/Button.jsx
- web/src/components/FriendGroup/FriendGroup.jsx
- web/src/components/Friendship/Friendship.jsx
- web/src/components/Navbar/Navbar.jsx
- web/src/components/Schedule/Schedule.jsx
- web/src/helpers/api.js
Closes:https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/19
Closes:https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/35 (leave group, soft delete)
Closes:https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/17 (automatic join)
> feat(web&backend): group schedule with shared events, leave and join group, search for group, search for friends

- backend/src/routes/friendship.js
- web/src/components/Friendship/FriendSchedule.jsx
- web/src/components/Friendship/Friendship.jsx
- web/src/helpers/api.js
- web/src/index.jsx
View a friend's schedule feature (#15)
- Successfully leads you to a new page that display's the chosen friend's schedule
Error handling for the case:
- Attempt to view an user's schedule who is not your friend
How I tested it:
- Logged in two different accounts and completed profiles for both
- Tried out the different view friend's schedule cases
> feat: View Friend's Schedule (ID015)

- backend/src/routes/friendGetter.js
- backend/src/routes/friendRequest.js
- backend/src/routes/friendship.js
- backend/src/server.js
- db/database.sql
- web/src/components/Friendship/FriendRequests.jsx
- web/src/components/Friendship/Friendship.jsx
- web/src/components/Navbar/Navbar.jsx
- web/src/helpers/api.js
- web/src/index.jsx
To use it: 
1. Create two accounts and fill in your profile info on both 
2. Go on "Search Friend" and press on "Request Friend" to request the other person 
3. Go on the other account and press on "View Friend Requests" and press accept/decline to add the person or to decline their request. 
Note: I doesn't seem to refresh on my end, but you can see the request disappearing when you change tabs
> ID012 - Responding to friend requests

- web/src/components/Friendship/FriendSchedule.jsx
- web/src/components/Schedule/Schedule.jsx
Done ID022_view_blocked_event, event displayed in gray for private events when viewing a friend's schedule
> Added private toggle to event modification window

- Gherkin Features/ID015_Viewing_Friend_Schedule.feature
- web/testing/cypress/e2e/ID015_Viewing_Friend_Schedule.cy.js
> test(web): ID015_Viewing_Friend_Schedule 

- web/testing/cypress/e2e/ID021_Unfriend_Another_User.cy.js
Closes: https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/21
> test(web): ID021_Unfriend_Another_User

- backend/src/routes/event.js
- backend/src/routes/friendship.js
- backend/src/routes/profile.js
- db/database.sql
- web/src/components/Navbar/Navbar.jsx
- web/src/components/Schedule/Invite.jsx
- web/src/components/Schedule/Schedule.jsx
- web/src/components/Schedule/ViewInvitations.jsx
- web/src/helpers/api.js
- web/src/index.jsx
Closes: https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/25
Flow for anyone that might need to test this:
The fact that the invitation has been accepted or not is not yet displayed on the invite sender side of things ("future" improvement todo)
> feat(web & backend & db): proper calendar start date, event invitation, friend search, more fixes

- web/testing/cypress/e2e/ID012_Responding_To_Friend_Requests.cy.js
Closes: https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/13
> test(web): ID012_Responding_To_Friend_Requests

- Gherkin Features/ID018_Leave_Group.feature
- web/testing/cypress/e2e/ID018_Leave_Group.cy.js
Closes: https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/154
Test for leaving a group
Note: The error handling could not have been tested since it required the 'Delete group' feature which was part of the features to implement for this sprint
> test(web) : ID018_Leave_Group
